/**
 * Mock Data for Demo Mode
 * Provides realistic UK property data and mock users for testing without a database
 */

import type { User } from './schema';

// Mock Users
export const DEMO_USERS = {
  buyer: {
    id: 1,
    openId: 'demo-buyer-001',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    loginMethod: 'google',
    role: 'public' as const,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    lastSignedIn: new Date(),
  } as User,
  vendor: {
    id: 2,
    openId: 'demo-vendor-001',
    name: 'James Smith',
    email: 'james@example.com',
    loginMethod: 'email',
    role: 'vendor' as const,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
    lastSignedIn: new Date(),
  } as User,
  agent: {
    id: 3,
    openId: 'demo-agent-001',
    name: 'Emma Wilson',
    email: 'emma@example.com',
    loginMethod: 'email',
    role: 'agent' as const,
    createdAt: new Date('2023-06-20'),
    updatedAt: new Date('2024-02-10'),
    lastSignedIn: new Date(),
  } as User,
  admin: {
    id: 4,
    openId: 'demo-admin-001',
    name: 'Admin User',
    email: 'admin@valory.com',
    loginMethod: 'email',
    role: 'admin' as const,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-02-10'),
    lastSignedIn: new Date(),
  } as User,
};

// Mock Properties - 20 properties across UK cities
export const DEMO_PROPERTIES = [
  {
    id: 1,
    addressNumber: '42',
    addressStreet: 'Baker Street',
    addressArea: 'Westminster',
    addressTown: 'London',
    addressCounty: 'Greater London',
    addressPostcode: 'W1A 1AA',
    postcodeOutcode: 'W1A',
    postcodeSector: 'W1A 1',
    latitude: 51.52373,
    longitude: -0.15849,
    localAuthority: 'Westminster',
    region: 'London',
    country: 'UK',
    uprn: 100023336156,
    propertyType: 'apartment' as const,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 850,
    price: 750000,
    status: 'active' as const,
    description: 'Elegant period flat in prestigious Westminster location. Original features include high ceilings, ornate cornicing, and period fireplaces.',
    title: 'Period Apartment in Westminster',
    address: '42 Baker Street, Westminster, London W1A 1AA',
    city: 'London',
    postcode: 'W1A 1AA',
    saves: 24,
    views: 342,
    daysOnMarket: 18,
    createdAt: '2024-02-08T10:30:00Z',
    agentId: 3,
  },
  {
    id: 2,
    addressNumber: '156',
    addressStreet: 'Sloane Street',
    addressArea: 'Chelsea',
    addressTown: 'London',
    addressCounty: 'Greater London',
    addressPostcode: 'SW3 2AQ',
    postcodeOutcode: 'SW3',
    postcodeSector: 'SW3 2',
    latitude: 51.4945,
    longitude: -0.1656,
    localAuthority: 'Kensington and Chelsea',
    region: 'London',
    country: 'UK',
    uprn: 100024057891,
    propertyType: 'house' as const,
    bedrooms: 5,
    bathrooms: 4,
    squareFeet: 3500,
    price: 3200000,
    status: 'active' as const,
    description: 'Stunning Victorian townhouse with original features, recently refurbished. South-facing garden, basement level conversion.',
    title: 'Victorian Townhouse in Chelsea',
    address: '156 Sloane Street, Chelsea, London SW3 2AQ',
    city: 'London',
    postcode: 'SW3 2AQ',
    saves: 67,
    views: 891,
    daysOnMarket: 12,
    createdAt: '2024-02-04T14:15:00Z',
    agentId: 3,
  },
  {
    id: 3,
    addressNumber: '87',
    addressStreet: 'Oxford Road',
    addressArea: 'City Centre',
    addressTown: 'Manchester',
    addressCounty: 'Greater Manchester',
    addressPostcode: 'M1 5BQ',
    postcodeOutcode: 'M1',
    postcodeSector: 'M1 5',
    latitude: 53.4792,
    longitude: -2.2453,
    localAuthority: 'Manchester',
    region: 'North West',
    country: 'UK',
    uprn: 100011425678,
    propertyType: 'apartment' as const,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 950,
    price: 375000,
    status: 'active' as const,
    description: 'Modern penthouse apartment in prime city centre location. Floor-to-ceiling windows with panoramic city views.',
    title: 'Modern Penthouse in Manchester City Centre',
    address: '87 Oxford Road, Manchester M1 5BQ',
    city: 'Manchester',
    postcode: 'M1 5BQ',
    saves: 19,
    views: 289,
    daysOnMarket: 22,
    createdAt: '2024-02-06T11:45:00Z',
    agentId: 3,
  },
  {
    id: 4,
    addressNumber: '23',
    addressStreet: 'Belgrave Road',
    addressArea: 'Edgbaston',
    addressTown: 'Birmingham',
    addressCounty: 'West Midlands',
    addressPostcode: 'B15 3ES',
    postcodeOutcode: 'B15',
    postcodeSector: 'B15 3',
    latitude: 52.4959,
    longitude: -1.9363,
    localAuthority: 'Birmingham',
    region: 'West Midlands',
    country: 'UK',
    uprn: 100012891234,
    propertyType: 'house' as const,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2800,
    price: 625000,
    status: 'active' as const,
    description: 'Impressive Victorian villa in sought-after Edgbaston. Period features, substantial grounds, recent upgrades.',
    title: 'Victorian Villa in Edgbaston',
    address: '23 Belgrave Road, Birmingham B15 3ES',
    city: 'Birmingham',
    postcode: 'B15 3ES',
    saves: 31,
    views: 456,
    daysOnMarket: 15,
    createdAt: '2024-02-07T09:20:00Z',
    agentId: 3,
  },
  {
    id: 5,
    addressNumber: '45',
    addressStreet: 'Clifton Triangle',
    addressArea: 'Clifton',
    addressTown: 'Bristol',
    addressCounty: 'Somerset',
    addressPostcode: 'BS8 2EY',
    postcodeOutcode: 'BS8',
    postcodeSector: 'BS8 2',
    latitude: 51.4644,
    longitude: -2.6147,
    localAuthority: 'Bristol, City of',
    region: 'South West',
    country: 'UK',
    uprn: 100013567890,
    propertyType: 'townhouse' as const,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 2100,
    price: 850000,
    status: 'active' as const,
    description: 'Georgian townhouse in exclusive Clifton Triangle. Period details, modern amenities, private parking.',
    title: 'Georgian Townhouse in Clifton',
    address: '45 Clifton Triangle, Bristol BS8 2EY',
    city: 'Bristol',
    postcode: 'BS8 2EY',
    saves: 28,
    views: 378,
    daysOnMarket: 19,
    createdAt: '2024-02-05T13:50:00Z',
    agentId: 3,
  },
  {
    id: 6,
    addressNumber: '127',
    addressStreet: 'Royal Mile',
    addressArea: 'Old Town',
    addressTown: 'Edinburgh',
    addressCounty: 'Midlothian',
    addressPostcode: 'EH1 2PB',
    postcodeOutcode: 'EH1',
    postcodeSector: 'EH1 2',
    latitude: 55.9525,
    longitude: -3.1903,
    localAuthority: 'City of Edinburgh',
    region: 'Scotland',
    country: 'UK',
    uprn: 100019876543,
    propertyType: 'apartment' as const,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 800,
    price: 425000,
    status: 'active' as const,
    description: 'Historic flat on iconic Royal Mile. Original stone work, wood beams, steps to castle.',
    title: 'Historic Flat on Royal Mile',
    address: '127 Royal Mile, Edinburgh EH1 2PB',
    city: 'Edinburgh',
    postcode: 'EH1 2PB',
    saves: 15,
    views: 267,
    daysOnMarket: 25,
    createdAt: '2024-02-03T16:20:00Z',
    agentId: 3,
  },
  {
    id: 7,
    addressNumber: '89',
    addressStreet: 'The Calls',
    addressArea: 'City Centre',
    addressTown: 'Leeds',
    addressCounty: 'West Yorkshire',
    addressPostcode: 'LS2 7EY',
    postcodeOutcode: 'LS2',
    postcodeSector: 'LS2 7',
    latitude: 53.8006,
    longitude: -1.5442,
    localAuthority: 'Leeds',
    region: 'Yorkshire and Humber',
    country: 'UK',
    uprn: 100011234567,
    propertyType: 'apartment' as const,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 920,
    price: 285000,
    status: 'active' as const,
    description: 'Contemporary loft conversion in converted warehouse. Exposed brick, floor-to-ceiling windows.',
    title: 'Modern Loft in Leeds City Centre',
    address: '89 The Calls, Leeds LS2 7EY',
    city: 'Leeds',
    postcode: 'LS2 7EY',
    saves: 22,
    views: 321,
    daysOnMarket: 17,
    createdAt: '2024-02-09T10:15:00Z',
    agentId: 3,
  },
  {
    id: 8,
    addressNumber: '67',
    addressStreet: 'Bold Street',
    addressArea: 'City Centre',
    addressTown: 'Liverpool',
    addressCounty: 'Merseyside',
    addressPostcode: 'L1 4DS',
    postcodeOutcode: 'L1',
    postcodeSector: 'L1 4',
    latitude: 53.4079,
    longitude: -2.9929,
    localAuthority: 'Liverpool',
    region: 'North West',
    country: 'UK',
    uprn: 100010567890,
    propertyType: 'apartment' as const,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 650,
    price: 185000,
    status: 'active' as const,
    description: 'Stylish studio apartment in regenerated Albert Dock area. Modern finishes, secure building.',
    title: 'Studio in Albert Dock',
    address: '67 Bold Street, Liverpool L1 4DS',
    city: 'Liverpool',
    postcode: 'L1 4DS',
    saves: 8,
    views: 145,
    daysOnMarket: 28,
    createdAt: '2024-01-28T14:30:00Z',
    agentId: 3,
  },
  {
    id: 9,
    addressNumber: '34',
    addressStreet: 'The Royal Crescent',
    addressArea: 'Bath City Centre',
    addressTown: 'Bath',
    addressCounty: 'Somerset',
    addressPostcode: 'BA1 2LR',
    postcodeOutcode: 'BA1',
    postcodeSector: 'BA1 2',
    latitude: 51.3857,
    longitude: -2.3633,
    localAuthority: 'Bath and North East Somerset',
    region: 'South West',
    country: 'UK',
    uprn: 100014567890,
    propertyType: 'apartment' as const,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1800,
    price: 650000,
    status: 'active' as const,
    description: 'Stunning apartment in iconic Georgian crescent. Original features, period charm, views of city.',
    title: 'Georgian Crescent Apartment',
    address: '34 The Royal Crescent, Bath BA1 2LR',
    city: 'Bath',
    postcode: 'BA1 2LR',
    saves: 36,
    views: 512,
    daysOnMarket: 10,
    createdAt: '2024-02-10T11:00:00Z',
    agentId: 3,
  },
  {
    id: 10,
    addressNumber: '56',
    addressStreet: 'High Street',
    addressArea: 'City Centre',
    addressTown: 'Oxford',
    addressCounty: 'Oxfordshire',
    addressPostcode: 'OX1 4BE',
    postcodeOutcode: 'OX1',
    postcodeSector: 'OX1 4',
    latitude: 51.7524,
    longitude: -1.2578,
    localAuthority: 'Oxford',
    region: 'South East',
    country: 'UK',
    uprn: 100015567890,
    propertyType: 'house' as const,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 2200,
    price: 775000,
    status: 'active' as const,
    description: 'Historic townhouse near University. Original quoins, period features, private courtyard.',
    title: 'Historic Townhouse in Oxford',
    address: '56 High Street, Oxford OX1 4BE',
    city: 'Oxford',
    postcode: 'OX1 4BE',
    saves: 19,
    views: 298,
    daysOnMarket: 20,
    createdAt: '2024-02-02T15:45:00Z',
    agentId: 3,
  },
  {
    id: 11,
    addressNumber: '89',
    addressStreet: 'Kings Parade',
    addressArea: 'City Centre',
    addressTown: 'Cambridge',
    addressCounty: 'Cambridgeshire',
    addressPostcode: 'CB2 1SJ',
    postcodeOutcode: 'CB2',
    postcodeSector: 'CB2 1',
    latitude: 52.2044,
    longitude: 0.1204,
    localAuthority: 'Cambridge',
    region: 'East Anglia',
    country: 'UK',
    uprn: 100016567890,
    propertyType: 'apartment' as const,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 900,
    price: 395000,
    status: 'active' as const,
    description: 'Elegant apartment overlooking The Backs. River views, close to colleges and city centre.',
    title: 'Riverside Apartment in Cambridge',
    address: '89 Kings Parade, Cambridge CB2 1SJ',
    city: 'Cambridge',
    postcode: 'CB2 1SJ',
    saves: 13,
    views: 223,
    daysOnMarket: 23,
    createdAt: '2024-02-01T12:30:00Z',
    agentId: 3,
  },
  {
    id: 12,
    addressNumber: '234',
    addressStreet: 'Knightsbridge',
    addressArea: 'Knightsbridge',
    addressTown: 'London',
    addressCounty: 'Greater London',
    addressPostcode: 'SW7 1BD',
    postcodeOutcode: 'SW7',
    postcodeSector: 'SW7 1',
    latitude: 51.502,
    longitude: -0.1672,
    localAuthority: 'Kensington and Chelsea',
    region: 'London',
    country: 'UK',
    uprn: 100023456789,
    propertyType: 'apartment' as const,
    bedrooms: 3,
    bathrooms: 3,
    squareFeet: 1950,
    price: 2100000,
    status: 'active' as const,
    description: 'Luxurious apartment in prestigious Knightsbridge. Concierge service, gym, secure parking.',
    title: 'Luxury Apartment in Knightsbridge',
    address: '234 Knightsbridge, London SW7 1BD',
    city: 'London',
    postcode: 'SW7 1BD',
    saves: 44,
    views: 678,
    daysOnMarket: 8,
    createdAt: '2024-02-11T09:00:00Z',
    agentId: 3,
  },
  {
    id: 13,
    addressNumber: '78',
    addressStreet: 'Deansgate',
    addressArea: 'City Centre',
    addressTown: 'Manchester',
    addressCounty: 'Greater Manchester',
    addressPostcode: 'M3 2FF',
    postcodeOutcode: 'M3',
    postcodeSector: 'M3 2',
    latitude: 53.4817,
    longitude: -2.2426,
    localAuthority: 'Manchester',
    region: 'North West',
    country: 'UK',
    uprn: 100011567890,
    propertyType: 'house' as const,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1100,
    price: 425000,
    status: 'active' as const,
    description: 'Contemporary townhouse in vibrant Deansgate. Open plan living, modern kitchen, roof terrace.',
    title: 'Contemporary Townhouse in Deansgate',
    address: '78 Deansgate, Manchester M3 2FF',
    city: 'Manchester',
    postcode: 'M3 2FF',
    saves: 17,
    views: 245,
    daysOnMarket: 21,
    createdAt: '2024-02-09T13:20:00Z',
    agentId: 3,
  },
  {
    id: 14,
    addressNumber: '92',
    addressStreet: 'Colmore Row',
    addressArea: 'City Centre',
    addressTown: 'Birmingham',
    addressCounty: 'West Midlands',
    addressPostcode: 'B3 2DB',
    postcodeOutcode: 'B3',
    postcodeSector: 'B3 2',
    latitude: 52.5067,
    longitude: -1.8935,
    localAuthority: 'Birmingham',
    region: 'West Midlands',
    country: 'UK',
    uprn: 100012567890,
    propertyType: 'apartment' as const,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1050,
    price: 325000,
    status: 'active' as const,
    description: 'Modern apartment in Grade II listed Victorian building. Period features, contemporary interiors.',
    title: 'Historic Building Apartment',
    address: '92 Colmore Row, Birmingham B3 2DB',
    city: 'Birmingham',
    postcode: 'B3 2DB',
    saves: 12,
    views: 189,
    daysOnMarket: 26,
    createdAt: '2024-01-31T10:40:00Z',
    agentId: 3,
  },
  {
    id: 15,
    addressNumber: '11',
    addressStreet: 'Park Street',
    addressArea: 'City Centre',
    addressTown: 'Bristol',
    addressCounty: 'Somerset',
    addressPostcode: 'BS1 5PB',
    postcodeOutcode: 'BS1',
    postcodeSector: 'BS1 5',
    latitude: 51.4563,
    longitude: -2.5891,
    localAuthority: 'Bristol, City of',
    region: 'South West',
    country: 'UK',
    uprn: 100013456789,
    propertyType: 'apartment' as const,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 875,
    price: 420000,
    status: 'active' as const,
    description: 'Spacious flat in converted Victorian warehouse. Industrial chic, exposed beams, city views.',
    title: 'Warehouse Conversion in Bristol',
    address: '11 Park Street, Bristol BS1 5PB',
    city: 'Bristol',
    postcode: 'BS1 5PB',
    saves: 21,
    views: 334,
    daysOnMarket: 14,
    createdAt: '2024-02-08T14:10:00Z',
    agentId: 3,
  },
  {
    id: 16,
    addressNumber: '45',
    addressStreet: 'Grassmarket',
    addressArea: 'Old Town',
    addressTown: 'Edinburgh',
    addressCounty: 'Midlothian',
    addressPostcode: 'EH1 2JU',
    postcodeOutcode: 'EH1',
    postcodeSector: 'EH1 2',
    latitude: 55.9486,
    longitude: -3.1924,
    localAuthority: 'City of Edinburgh',
    region: 'Scotland',
    country: 'UK',
    uprn: 100019567890,
    propertyType: 'house' as const,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1950,
    price: 580000,
    status: 'active' as const,
    description: 'Historic townhouse in bustling Grassmarket. Character features, close to museums and shops.',
    title: 'Historic Townhouse in Grassmarket',
    address: '45 Grassmarket, Edinburgh EH1 2JU',
    city: 'Edinburgh',
    postcode: 'EH1 2JU',
    saves: 18,
    views: 267,
    daysOnMarket: 24,
    createdAt: '2024-02-04T11:25:00Z',
    agentId: 3,
  },
  {
    id: 17,
    addressNumber: '123',
    addressStreet: 'Corn Exchange Street',
    addressArea: 'City Centre',
    addressTown: 'Leeds',
    addressCounty: 'West Yorkshire',
    addressPostcode: 'LS1 6AB',
    postcodeOutcode: 'LS1',
    postcodeSector: 'LS1 6',
    latitude: 53.8008,
    longitude: -1.5463,
    localAuthority: 'Leeds',
    region: 'Yorkshire and Humber',
    country: 'UK',
    uprn: 100011345678,
    propertyType: 'apartment' as const,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1000,
    price: 315000,
    status: 'active' as const,
    description: 'Modern apartment in converted Grade II listed building. Original architecture, high specification.',
    title: 'Listed Building Apartment in Leeds',
    address: '123 Corn Exchange Street, Leeds LS1 6AB',
    city: 'Leeds',
    postcode: 'LS1 6AB',
    saves: 14,
    views: 198,
    daysOnMarket: 27,
    createdAt: '2024-01-30T16:50:00Z',
    agentId: 3,
  },
  {
    id: 18,
    addressNumber: '156',
    addressStreet: 'Lord Street',
    addressArea: 'City Centre',
    addressTown: 'Liverpool',
    addressCounty: 'Merseyside',
    addressPostcode: 'L2 1TG',
    postcodeOutcode: 'L2',
    postcodeSector: 'L2 1',
    latitude: 53.4072,
    longitude: -2.9849,
    localAuthority: 'Liverpool',
    region: 'North West',
    country: 'UK',
    uprn: 100010678901,
    propertyType: 'house' as const,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 950,
    price: 225000,
    status: 'active' as const,
    description: 'Charming Victorian townhouse on prestigious Lord Street. Recent renovation, period features.',
    title: 'Victorian Townhouse in Liverpool',
    address: '156 Lord Street, Liverpool L2 1TG',
    city: 'Liverpool',
    postcode: 'L2 1TG',
    saves: 9,
    views: 167,
    daysOnMarket: 29,
    createdAt: '2024-01-25T13:15:00Z',
    agentId: 3,
  },
  {
    id: 19,
    addressNumber: '78',
    addressStreet: 'Pulteney Street',
    addressArea: 'Bath City Centre',
    addressTown: 'Bath',
    addressCounty: 'Somerset',
    addressPostcode: 'BA2 4DG',
    postcodeOutcode: 'BA2',
    postcodeSector: 'BA2 4',
    latitude: 51.3797,
    longitude: -2.3539,
    localAuthority: 'Bath and North East Somerset',
    region: 'South West',
    country: 'UK',
    uprn: 100014678901,
    propertyType: 'apartment' as const,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1100,
    price: 520000,
    status: 'active' as const,
    description: 'Elegant apartment in Georgian terrace. Period cornicing, fireplaces, large sash windows.',
    title: 'Georgian Apartment in Bath',
    address: '78 Pulteney Street, Bath BA2 4DG',
    city: 'Bath',
    postcode: 'BA2 4DG',
    saves: 16,
    views: 234,
    daysOnMarket: 16,
    createdAt: '2024-02-07T10:55:00Z',
    agentId: 3,
  },
  {
    id: 20,
    addressNumber: '234',
    addressStreet: 'St Aldates',
    addressArea: 'City Centre',
    addressTown: 'Oxford',
    addressCounty: 'Oxfordshire',
    addressPostcode: 'OX1 1BW',
    postcodeOutcode: 'OX1',
    postcodeSector: 'OX1 1',
    latitude: 51.7493,
    longitude: -1.2615,
    localAuthority: 'Oxford',
    region: 'South East',
    country: 'UK',
    uprn: 100015678901,
    propertyType: 'house' as const,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2600,
    price: 995000,
    status: 'active' as const,
    description: 'Impressive Victorian property near Christchurch. Large rooms, original features, private parking.',
    title: 'Victorian Property near Christchurch',
    address: '234 St Aldates, Oxford OX1 1BW',
    city: 'Oxford',
    postcode: 'OX1 1BW',
    saves: 26,
    views: 395,
    daysOnMarket: 13,
    createdAt: '2024-02-06T15:30:00Z',
    agentId: 3,
  },
];

// Mock Timeline Events
export const DEMO_TIMELINE_EVENTS = [
  { propertyId: 1, type: 'launched' as const, title: 'Property Launched', timestamp: '2024-02-08T10:30:00Z' },
  { propertyId: 1, type: 'viewing_booked' as const, title: '3 Viewings Booked', timestamp: '2024-02-09T14:20:00Z' },
  { propertyId: 1, type: 'media_uploaded' as const, title: 'Photos Uploaded', timestamp: '2024-02-09T16:45:00Z' },

  { propertyId: 2, type: 'launched' as const, title: 'Property Launched', timestamp: '2024-02-04T14:15:00Z' },
  { propertyId: 2, type: 'viewing_booked' as const, title: '8 Viewings Booked', timestamp: '2024-02-05T10:30:00Z' },
  { propertyId: 2, type: 'viewing_milestone' as const, title: 'Viewing Milestone Reached', timestamp: '2024-02-06T12:00:00Z' },
  { propertyId: 2, type: 'offer_received' as const, title: 'Offer Received', timestamp: '2024-02-07T09:15:00Z' },

  { propertyId: 5, type: 'launched' as const, title: 'Property Launched', timestamp: '2024-02-05T13:50:00Z' },
  { propertyId: 5, type: 'viewing_booked' as const, title: '5 Viewings Booked', timestamp: '2024-02-06T11:20:00Z' },
  { propertyId: 5, type: 'media_uploaded' as const, title: '360 Tour Uploaded', timestamp: '2024-02-07T14:30:00Z' },
];

// Mock Followed Properties (for demo buyer)
export const DEMO_FOLLOWED_PROPERTIES = [1, 2, 5, 9];

// Mock Valuations
export const DEMO_VALUATIONS = [
  {
    id: 1,
    propertyId: 1,
    vendorId: 2,
    status: 'accepted' as const,
    estimatedLowPrice: 700000,
    estimatedHighPrice: 800000,
    confidence: 'high' as const,
    acceptedAt: '2024-02-10T11:30:00Z',
    createdAt: '2024-02-08T10:00:00Z',
  },
  {
    id: 2,
    propertyId: 5,
    vendorId: 2,
    status: 'pending' as const,
    estimatedLowPrice: 800000,
    estimatedHighPrice: 900000,
    confidence: 'medium' as const,
    acceptedAt: null,
    createdAt: '2024-02-05T12:00:00Z',
  },
  {
    id: 3,
    propertyId: 12,
    vendorId: 2,
    status: 'completed' as const,
    estimatedLowPrice: 2000000,
    estimatedHighPrice: 2200000,
    confidence: 'high' as const,
    acceptedAt: '2024-02-01T09:00:00Z',
    createdAt: '2024-01-28T14:00:00Z',
  },
];

// Matched agents returned to sellers after lead capture
export const DEMO_MATCHED_AGENTS = [
  {
    id: 101,
    name: 'Sarah Mitchell',
    agency: 'Fenyx Rose Estates',
    title: 'Senior Valuer',
    coverageLabel: 'Crewkerne, Ilminster, Chard',
    coveragePostcodes: ['TA18', 'TA19', 'TA20', 'TA17'],
    yearsExperience: 8,
    propertiesSoldLocal: 47,
    avgSaleTimeDays: 42,
    qualityScore: 88,
    specialisms: ['Character homes', 'Rural properties', 'First-time sellers'],
    bio: 'Specialist in Somerset character properties with a focus on honest, data-led valuations.',
  },
  {
    id: 102,
    name: 'Tom Hartley',
    agency: 'Hartley & Co',
    title: 'Director',
    coverageLabel: 'Chard, Crewkerne, Axminster',
    coveragePostcodes: ['TA20', 'TA18', 'EX13'],
    yearsExperience: 14,
    propertiesSoldLocal: 83,
    avgSaleTimeDays: 38,
    qualityScore: 91,
    specialisms: ['Period homes', 'Downsizing', 'Land & development'],
    bio: 'Established independent agency covering south Somerset and east Devon since 2010.',
  },
  {
    id: 103,
    name: 'Rebecca Oakes',
    agency: 'Oliver James Property',
    title: 'Associate Director',
    coverageLabel: 'Ilminster, Chard, South Petherton',
    coveragePostcodes: ['TA19', 'TA20', 'TA13'],
    yearsExperience: 6,
    propertiesSoldLocal: 34,
    avgSaleTimeDays: 51,
    qualityScore: 82,
    specialisms: ['Family homes', 'New builds', 'Lettings'],
    bio: 'Dedicated to a personal, low-pressure approach for sellers at every stage.',
  },
];

export type MatchedAgent = typeof DEMO_MATCHED_AGENTS[number];

// Mock Agent Stats
export const DEMO_AGENT_STATS = {
  totalListings: 6,
  totalFollowers: 42,
  totalEvents: 18,
};

// Mock Postcode Data
export const DEMO_POSTCODES = {
  'W1A 1AA': {
    postcode: 'W1A 1AA',
    adminDistrict: 'Westminster',
    region: 'London',
    country: 'England',
    adminWard: 'West End',
    outcode: 'W1A',
    incode: '1AA',
  },
  'SW3 2AQ': {
    postcode: 'SW3 2AQ',
    adminDistrict: 'Kensington and Chelsea',
    region: 'London',
    country: 'England',
    adminWard: 'Chelsea',
    outcode: 'SW3',
    incode: '2AQ',
  },
  'M1 5BQ': {
    postcode: 'M1 5BQ',
    adminDistrict: 'Manchester',
    region: 'North West',
    country: 'England',
    adminWard: 'City Centre',
    outcode: 'M1',
    incode: '5BQ',
  },
  'B15 3ES': {
    postcode: 'B15 3ES',
    adminDistrict: 'Birmingham',
    region: 'West Midlands',
    country: 'England',
    adminWard: 'Edgbaston',
    outcode: 'B15',
    incode: '3ES',
  },
  'BS8 2EY': {
    postcode: 'BS8 2EY',
    adminDistrict: 'Bristol, City of',
    region: 'South West',
    country: 'England',
    adminWard: 'Clifton',
    outcode: 'BS8',
    incode: '2EY',
  },
  'EH1 2PB': {
    postcode: 'EH1 2PB',
    adminDistrict: 'City of Edinburgh',
    region: 'Scotland',
    country: 'Scotland',
    adminWard: 'Old Town',
    outcode: 'EH1',
    incode: '2PB',
  },
  'LS2 7EY': {
    postcode: 'LS2 7EY',
    adminDistrict: 'Leeds',
    region: 'Yorkshire and Humber',
    country: 'England',
    adminWard: 'City Centre',
    outcode: 'LS2',
    incode: '7EY',
  },
  'L1 4DS': {
    postcode: 'L1 4DS',
    adminDistrict: 'Liverpool',
    region: 'North West',
    country: 'England',
    adminWard: 'City Centre',
    outcode: 'L1',
    incode: '4DS',
  },
  'BA1 2LR': {
    postcode: 'BA1 2LR',
    adminDistrict: 'Bath and North East Somerset',
    region: 'South West',
    country: 'England',
    adminWard: 'City Centre',
    outcode: 'BA1',
    incode: '2LR',
  },
  'OX1 4BE': {
    postcode: 'OX1 4BE',
    adminDistrict: 'Oxford',
    region: 'South East',
    country: 'England',
    adminWard: 'City Centre',
    outcode: 'OX1',
    incode: '4BE',
  },
  'CB2 1SJ': {
    postcode: 'CB2 1SJ',
    adminDistrict: 'Cambridge',
    region: 'East Anglia',
    country: 'England',
    adminWard: 'City Centre',
    outcode: 'CB2',
    incode: '1SJ',
  },
  'SW7 1BD': {
    postcode: 'SW7 1BD',
    adminDistrict: 'Kensington and Chelsea',
    region: 'London',
    country: 'England',
    adminWard: 'Knightsbridge',
    outcode: 'SW7',
    incode: '1BD',
  },
  'M3 2FF': {
    postcode: 'M3 2FF',
    adminDistrict: 'Manchester',
    region: 'North West',
    country: 'England',
    adminWard: 'City Centre',
    outcode: 'M3',
    incode: '2FF',
  },
  'B3 2DB': {
    postcode: 'B3 2DB',
    adminDistrict: 'Birmingham',
    region: 'West Midlands',
    country: 'England',
    adminWard: 'City Centre',
    outcode: 'B3',
    incode: '2DB',
  },
  'BS1 5PB': {
    postcode: 'BS1 5PB',
    adminDistrict: 'Bristol, City of',
    region: 'South West',
    country: 'England',
    adminWard: 'City Centre',
    outcode: 'BS1',
    incode: '5PB',
  },
  'EH1 2JU': {
    postcode: 'EH1 2JU',
    adminDistrict: 'City of Edinburgh',
    region: 'Scotland',
    country: 'Scotland',
    adminWard: 'Old Town',
    outcode: 'EH1',
    incode: '2JU',
  },
  'LS1 6AB': {
    postcode: 'LS1 6AB',
    adminDistrict: 'Leeds',
    region: 'Yorkshire and Humber',
    country: 'England',
    adminWard: 'City Centre',
    outcode: 'LS1',
    incode: '6AB',
  },
  'L2 1TG': {
    postcode: 'L2 1TG',
    adminDistrict: 'Liverpool',
    region: 'North West',
    country: 'England',
    adminWard: 'City Centre',
    outcode: 'L2',
    incode: '1TG',
  },
  'BA2 4DG': {
    postcode: 'BA2 4DG',
    adminDistrict: 'Bath and North East Somerset',
    region: 'South West',
    country: 'England',
    adminWard: 'City Centre',
    outcode: 'BA2',
    incode: '4DG',
  },
  'OX1 1BW': {
    postcode: 'OX1 1BW',
    adminDistrict: 'Oxford',
    region: 'South East',
    country: 'England',
    adminWard: 'City Centre',
    outcode: 'OX1',
    incode: '1BW',
  },
};
